modules:
  - data_ingestion
  - classification
  - db_update


data_ingestion:
  test: true  # Enable test mode for data ingestion
  
classification:
  test: true  # Enable test mode for classification
  codes:
    - code: "snid"
      config_file: "/path/to/snid/config.yml"
    - code: "ngsf"
      config_file: "/path/to/other_code/config.yml"
db_creds:
  host: "localhost"
  port: 5432
  user: "pwise"
  password: ""
data_paths:
  deliveries_dir: "Users/pwise/4MOST/tides/test_data/tides_test"  
  archive_dir: "Users/pwise/4MOST/tides/test_data/archive"
  spectra_dir: "Users/pwise/4MOST/tides/test_data/spectra/2025-06-05"  # Example: Random night from the last week