modules:
  - data_ingestion
  - classification_api


data_ingestion:
  test: true  # Enable test mode for data ingestion
  
classification:
  test: true  # Enable test mode for classification
  enabled_classifiers:  # Which classifiers to run
    - snid
    #- ngsf
    # - qxp  # Add qxp when available
  codes:
    - code: "snid"
      config_file: "/path/to/snid/config.yml"
    - code: "ngsf"
      config_file: "/path/to/other_code/config.yml"
db_creds:
  host: "localhost"
  port: 5432
  user: "pwise"
  password: ""
data_paths:
  deliveries_dir: "/data/deliveries"  # Container path for deliveries
  archive_dir: "/data/archive"
  spectra_dir: "/data/spectra"  # Container path for spectra
  #static_plots_dir: "/data/static/plots"
snid:
  defaults:
    wmin: 4000
    wmax: 9000
    zmin: 0.1
    zmax: 1.2
    emclip:
    emwid: 40
    agemin: -90
    agemax: 1000
    aband: false
    use:
      - Ia
      - Ib
      - Ic
      - II
      - NotSN
    avoid: []
    avoidsub: []
    usesub: []